stages:
  preprocess:
    cmd: uv run python src/training/preprocess.py
    deps:
      - data/raw/train.csv
      - src/training/preprocess.py
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.npy
      - data/processed/y_test.npy
      - models/encoder.pkl
    params:
      - encoder_name

  train:
    cmd: uv run python src/training/train.py
    deps:
      - data/processed/X_train.csv
      - data/processed/y_train.npy
      - src/training/train.py
    outs:
      - models/model.pkl
    params:
      - model.model_name
      - model.max_depth
      - model.min_samples_leaf
      - model.max_features

  evaluate:
    cmd: uv run python src/training/evaluate.py
    deps:
      - data/processed/X_test.csv
      - data/processed/y_test.npy
      - models/model.pkl
      - src/training/evaluate.py